language: java
dist: trusty
jdk: oraclejdk8
cache:
  bundler: true
  directories:
    - $HOME/.m2
    - $HOME/docker
addons:
  apt:
    packages:
      - net-tools
services:
  - docker

script:
  - export HOST_IP=$(ifconfig docker0 | awk -F"[:, ]+" '/inet/ {print $4}')
  - echo "$DOCKER_PAS" | docker login --username "$DOCKER_USER" --password-stdin
  - docker-compose -f ./selenium-grid/docker-compose.yaml up -d
  - . ./selenium-grid/wait-for-grid.sh && mvn clean test
  - docker-compose -f ./selenium-grid/docker-compose.yaml down